name: Create Archive
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1-beta
        id: setup-ffmpeg
      - name: Execute ffmpeg
        run: ffmpeg -loop 1 -i origin/2.jpeg -i origin/2.mp3 -c:v libx264 -s 526x648 -crf 18 -c:a aac -strict-vf "drawtext=fontfile=fonts/Cinzel-VariableFont_wght.ttf:text='Fresh Off The Boat':fontsize=46:fontcolor=white:shadowcolor=black:shadowx=1:shadowy=1:x=W*(1-0.05*t):y=H+descent-ascent" experimental  -b:a 192k -shortest processed/${{ env.VIDEO }}  
      - name: Check to see if a new video file has been created
        id: changes
        run: |
          git add -N .
          echo "::set-output name=count::$(git diff --name-only | wc -l)"
      - name: Commit files
        run: |
          git config --local user.email "whxcctv@users.noreply.github.com"
          git config --local user.name "whxcctv"
          git add ./output/*
          git commit -m "Add changes" -a
        if: steps.changes.outputs.count > 0
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        if: steps.changes.outputs.count > 0
